### ISSUE TITLE
VERY large log files

### ISSUE THREAD

**Issue by cbryant02** [lekeno/edr#310] opened 2020-05-28 01:32 UTC
Ran out of disk space on my main drive, despite having ~70GB left a few days ago. Looks like EDMCOverlay is the culprit.

![image](https://user-images.githubusercontent.com/12358075/83088079-63ca7400-a058-11ea-9373-e31301a95395.png)

[Issue #16](https://github.com/inorton/EDMCOverlay/issues/16) over at the EDMCOverlay repo is this exact problem, but it was fixed in 1.0.1. Either the bug has reappeared or the bundled version of EDMCOverlay just needs to be updated.

**Comment by lekeno** [comment] 2020-06-06 02:24
Thanks for the report, I think you are right that this is the same issue.
I will see if I can bring a new version of the overlay.

In the meantime, the suggested workaround is to `Exit Elite or terminate the EDMCOverlay process and delete the log file if it's sticks around.` The issue occurs when the overlay is running and EDMC is restarted. The overlay will shutdown itself upon exiting Elite (hence the workaround).

**Comment by UnholyGnomes** [comment] 2022-01-19 05:14
I've just encountered the same issue, ~97 gigs of space taken up by edmcoverlay.log.

**Comment by inorton** [comment] 2022-01-20 07:07
Oops! maybe I don't need a new SSD afterall!

**Comment by inorton** [comment] 2022-01-20 07:10
@UnholyGnomes  You should be able to try using the latest EDMCOverlay, it now works with EDR and has some other fixes in

**Comment by lekeno** [comment] 2022-05-15 06:42
The issue is confirmed to be fixed in the latest versions of the overlay.

**Closed by lekeno** 2022-05-15 06:42 UTC
