### ISSUE TITLE
Incompatible with autopath EDMC plugin

### ISSUE THREAD

**Issue by Paspasote** [lekeno/edr#246] opened 2019-08-07 13:37 UTC
EDMC runs well with one of them (either edr or autopath) but It does not run with both installed.

**Comment by lekeno** [comment] 2019-08-09 05:27
Thanks for filing an issue. Could you check your temp folder for a file named EDMarketConnector.log ? Open it with notepad, and let me know if you can spot specific errors (redact your username in the path, etc).

I'll see if I can reproduce on my end too.

**Comment by Sognus** [comment] 2019-08-11 01:39
Hello,

This issue was caused by [EDMC Autopath](https://github.com/Sognus/EDMC-Autopath). I pushed a fix into it's 1.1.0 version release. Please mark any issues using EDMC Autopath version 1.0.0 as wontfix.

Thanks, 
EDMC Autopath Author.

**Closed** 2019-09-01 02:47 UTC
